### ISSUE TITLE
Collaboration to incorporate this functionality into dotnet-outdated

### ISSUE THREAD

**Issue by coderpatros** [rychlym/dotnet-tools-outdated#1]
Hi @rychlym 

One of the maintainers of [dotnet-outdated](https://github.com/dotnet-outdated/dotnet-outdated) here.

I'd like to incorporate this functionality into dotnet-outdated. It's also MIT licensed. But I didn't want to just start copying your code without reaching out to you.

I have plenty on at the moment. So it will be a while before I even start looking at this in detail. But wanted to start the conversation.

**Comment by rychlym** [comment]
Hi @coderpatros 

Thanks for informing me. I am ok with using the code from this project on your. As you can see I haven't much time to keep this tool updated and add additional functionality about automatic update of the outdated packages - the -u switch, so I will be happy if someone can continue.  So I wish you good luck with your planned work!

**Comment by rychlym** [comment]
Hi @coderpatros  again,

Oh I realized I actually inspired also with settings and might be even with some code from your own project at the time I started with this! So it is my pleasure, it could serve to you.
 
On the other hand, I was thinking a couple days ago to release a version build on .net5. But what do you think - would it be better for you to keep the tool in a  low profile?

**Comment by coderpatros** [comment]
Thanks @rychlym. Don't let this put any of your plans on hold. It will probably be a while before I get to this.
