### ISSUE TITLE
Work with .NET local tools

### ISSUE THREAD

**Issue by menees** [rychlym/dotnet-tools-outdated#7]
Is there a way to make this work with [.NET local tools](https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-local-tool), which were added in .NET Core 3.0?

I've tried specifying `--toolPath .\.config\dotnet-tools.json` to point to my solution's local tools configuration, but that doesn't work. I've also tried using the `--name` option to pass in each local tool name one at a time, and that doesn't work. It seems to only try to lookup tool names if they're in the global tools.

**Comment by rychlym** [comment]
I am sorry, but the .NET local tools aren't implemented yet. To be honest, nobody needed that yet and I was quite lazy to even read the doc about that :) From that all, it might be also confusing that –toolPath
which is still for checking globally installed dotnet tools (but somehow manually moved to a custom location – really hardly to be used)

So after a little checking, I can see, it is really worth to add such a functionality. Well, I will need some time to implement and test it. (the --toolPath will be probably changed to --globalToolsPath (or --globalToolsStoreLocation)

**Comment by rychlym** [comment]
Hopefully a good message - the new version 0.7.0 supporting the local .NET tools is out. I needed quite a bunch of extra time to work out (probably less used) xml and json format output types and some breaking changes there (the release notes can be found at the https://www.nuget.org/packages/dotnet-tools-outdated/0.7.0)

btw. I must  take back my previous comment "(but somehow manually moved to a custom location – really hardly to be used)" - that is related to a [real documented scenario](https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-global-tool-in-a-custom-location)

**Comment by menees** [comment]
Thanks for the quick support! I'll try it out on Monday when I get back to the office.

**Comment by menees** [comment]
Thanks! This works great for me, and I really appreciate the quick resolution.

I noticed one minor change that seems like a typo. The `--output` option was changed to `--otput` in [this diff](https://github.com/rychlym/dotnet-tools-outdated/commit/1faf144244c5e051ea0e0c83aa9a46f693cbe934#diff-24396fb62b515b654ed14df13c46c0763edc7aede43b38388cdcd46da9c9bb97).
